
spring:
  jackson:
    serialization:
      indent-output: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://service-discovery-container:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE:service-discovery-container}


